[package]
name = "eventuler"
version = "0.1.0"
authors = ["Hyuksang Gwon"]
edition = "2018"

[dependencies]
actix-rt = "1.1.1"
actix-web = "2"
chrono = { version = "0.4", features = ["serde"] }
daggy = "0.7"
env_logger = "0.7"
thiserror = "1"
serde = "1.0"
serde_json = "1.0"
